orion:
  image: fiware/orion
  links:
    - mongo
    - accumulator
    - fiware-sth-comet
  ports:
    - "1026:1026"
  command: -dbhost mongo
mongo:
  image: mongo:3.2
  command: --smallfiles --nojournal
  ports:
    - "27018:27017" # port opened only for development environment
accumulator:
  build: accumulator
  ports:
    - "1028:1028"
  command: ./accumulator-server.py
fiware-sth-comet:
  build: fiware-sth-comet
  ports:
    - "8666:8666"
  environment:
    - STH_HOST=0.0.0.0
    - DB_URI=db:27017
  links:
    - db
db:
  image: mongo:3.2
  ports:
    - "27019:27017" # port opened only for development environment
